services:
  - type: web
    name: wolfy-bot
    env: node
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: DEFAULT_PREFIX
        value: "!"
      - key: BOT_STATUS
        value: "Watching the pack 🐺"
      - key: BOT_STATUS_TYPE
        value: WATCHING
      - key: BOT_ONLINE_STATUS
        value: online
      - key: TWITCH_CLIENT_ID
        sync: false
      - key: TWITCH_CLIENT_SECRET
        sync: false
